version: '3'
services:
  postgres:
    image: postgres
    restart: 'always'
    container_name: 'postgres'
    ports:
      - '5432:5432' # docker container port 5432, host port 5432
    volumes:
      - './db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo 